#!/usr/bin/env bash
#Show data about subdomains
func () {
    if [ -n "$2" ]
    then
      dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v x="$2" '$1=x{print "The subdomain "$1" is a "$4" record and points to "$5""}'
    else
      dig "www.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain www is a "$4" record and points to "$5""}'
      dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain lb-01 is a "$4" record and points to "$5""}'
      dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-01 is a "$4" record and points to "$5""}'
      dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain web-02 is a "$4" record and points to "$5""}' 
    fi
}
func "$1" "$2"
