#!/usr/bin/env bash
# etc/passwd con while

while IFS=":" read -r username password uid gid gecos home command; do
	echo "The user $username is part of the $gid gang, lives in $home and rides $command. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd
