#!/usr/bin/env bash
# badluck x4 goodluck x8

counter=1
while [ $counter -le 10 ]
do
	if [ $counter == 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
